### ISSUE TITLE
ImportError: No module named 'log_colors'

### ISSUE THREAD

**Issue by ghost** [cocomelonc/vulnexipy#1]
from log_colors import *
ImportError: No module named 'log_colors'

pip install colorlog
Collecting colorlog
  Downloading colorlog-4.2.1-py2.py3-none-any.whl (14 kB)
Installing collected packages: colorlog
Successfully installed colorlog-4.2.1

**Comment by cocomelonc** [comment]
It's not colorlog. It's file into the repository.
Please, clone the repository:
```bash
git clone https://github.com/cocomelonc/vulnexipy
```
go to the dir:
```bash
cd vulnexipy
```

and run, for example:
```bash
python cve_2017_1000119.py --url http://10.10.6.16 -user admin -pswd admin -lhost 10.10.14.16 -lport 4444
```

**Comment by cocomelonc** [comment]
@weirufa if you don't want to clone all repository, please add to your cve file, for example:
```python
class LogColors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    PURPLE = '\033[95m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
```
